### ISSUE TITLE
"ShaderProgram is unsupported" on low-end device causing instant crash on startup

### ISSUE THREAD

**Issue by ArgoreOfficial** [Muushy/Sprocket-Feedback#319]
Not me but BalIer#5450 in the Discord server, also seen it happen to some other people.

Game fails to load due to "ShaderProgram being unsupported", possibly either a [particle trails system or hdrp decals](https://forum.unity.com/threads/shaderprogram-is-unsupported-but-because-jobified-rendering-is-enabled-the-shaderprogram-can-not.952889/#:~:text=Cherio4%20said%3A%20%E2%86%91-,disabling%20HDRP%20Decals%20solved%20the%20error%20message%20spamming,caused%20by%20the%20presence%20of%20a%20%22Trails%22%20system%20in%20a%20VFX,-graph.%0A%0ASo) related issue.

Their specs:
![image](https://user-images.githubusercontent.com/45431685/219824234-1c37f1b0-70b9-412b-893d-532184fcc828.png)
Their logs:
![image](https://user-images.githubusercontent.com/45431685/219824221-518c1ebb-66ef-4969-a618-7355743d245a.png)

**Comment by Muushy** [comment]
Caused by old graphics processors, which can't physically render something in the game.
Only fix is removing the offending shaders (reworking graphics of parts/environment objects).

If it's only happening on certain parts or maps, let me know and I'll have a look. 
If you're going black on the main menu then it's never going to work on your specs.

Believe there have been similar issues with the netting on the bustle rack, though this to be confirmed.
